### ISSUE TITLE
Bump to matplotlib 3

### ISSUE THREAD

**Issue by pythonjam** [unibe-cns/NEAT#114]
When installing NEAT under Ubuntu Linux 18, by default the newest version of matplotlib (currently 3.3.3) gets installed. However this version is not compatible and needs to be downgraded.

Traceback (most recent call last):
  File "/home/name/blah/NEAT/examples/models/channels/TestCaseEvaluation.py", line 7, in <module>
    from examples.models.channels.channels_hay import Na_Ta
  File "/home/name/blah/NEAT/examples/models/channels/channels_hay.py", line 3, in <module>
    from neat import IonChannel
  File "/home/name/blah/NEAT/neat/__init__.py", line 13, in <module>
    from .trees.morphtree import MorphTree
  File "/home/name/blah/NEAT/neat/trees/morphtree.py", line 17, in <module>
    from mpl_toolkits.axes_grid1 import make_axes_locatable
  File "/home/name/.local/lib/python3.6/site-packages/mpl_toolkits/axes_grid1/__init__.py", line 3, in <module>
    from .axes_grid import Grid, ImageGrid, AxesGrid
  File "/home/name/.local/lib/python3.6/site-packages/mpl_toolkits/axes_grid1/axes_grid.py", line 22, in <module>
    class CbarAxesBase:
  File "/home/name/.local/lib/python3.6/site-packages/mpl_toolkits/axes_grid1/axes_grid.py", line 29, in CbarAxesBase
    @cbook._rename_parameter("3.2", "locator", "ticks")
AttributeError: module 'matplotlib.cbook' has no attribute '_rename_parameter'

The workaround is to downgrade to 2.2.5 with
pip3 install --upgrade matplotlib==2.2.5

In the long term it may be a good idea to upgrade to matplotlib 3

We should probably at least edit the requirements.txt with something like
matplotlib>=2.1.2,<=2.2.5

**Comment by benelot** [comment]
@WillemWybo I think it would be great anyway if our requirements would be bounded and >= alone. This leads to exactly the case we experience here that an fresh install leads to the user pulling all the newest releases, which might be breaking. I think it would be best to encode at least all the highest minor versions into the file based on the current minimum requirement (major.minor.bug on the version list). What is weird is why the build system still works with it as this should occur there.

**Comment by WillemWybo** [comment]
Strange, I upgraded my matplotlib to version 3.3.3 (Python version 3.7.6) and I can't reproduce the problem. All tests pass for me. 

@benelot Don't we run the risk then of ending up with an outdated software tool? At least if the tests uncover problems related to new versions of software on which NEAT depends, we can update NEAT and stay up to date.
@pythonjam seems like this is a matplotlib bug? when you just run `from mpl_toolkits.axes_grid1 import make_axes_locatable` in a python console, do you experience the same problem?

**Comment by WillemWybo** [comment]
I googled for the error, and while I don't find an exact reproduction, is seems similar errors occur when multiple versions of matplotlib are installed (eg [https://github.com/matplotlib/matplotlib/issues/17128](https://github.com/matplotlib/matplotlib/issues/17128) or [https://stackoverflow.com/questions/53421905/matplotlib-attributeerror-module-matplotlib-cbook-has-no-attribute-define-a](https://stackoverflow.com/questions/53421905/matplotlib-attributeerror-module-matplotlib-cbook-has-no-attribute-define-a) )

**Comment by benelot** [comment]
@WillemWybo Our software tool ends up outdated if we do not update the tool :) The illusion of always being up to date by allowing the users to install the library with the newest libraries is very trappy, as you basically let users test your package with library versions you probably did not test with (as they might get incompatible in the future). It would be better to be sure with which libraries it works and set those than to optimistically believe it will work forever when it surely does not. I'd rather install a very old version of matplotlib and be fine with it than having a broken library, and our users need to fix it. To stay up to date, we need to test from time to time if NEAT still works with newer versions, if so, bump up the maximal library version defintion, else actively migrate to the newer library or stay with the old definition.

**Comment by pythonjam** [comment]
I did a binary search to find out at which version the problem starts for me and it's actually after 3.1.0. So the first version that causes errors is 3.1.1 (note this error is different, but similar in nature):

Traceback (most recent call last):
  File "/home/name/blah/NEAT/examples/models/channels/TestCaseEvaluation.py", line 7, in <module>
    from examples.models.channels.channels_hay import Na_Ta
  File "/home/name/blah/NEAT/examples/models/channels/channels_hay.py", line 3, in <module>
    from neat import IonChannel
  File "/home/name/blah/NEAT/neat/__init__.py", line 13, in <module>
    from .trees.morphtree import MorphTree
  File "/home/name/blah/NEAT/neat/trees/morphtree.py", line 18, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/home/name/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/home/name/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 34, in <module>
    from . import axis3d
  File "/home/name/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axis3d.py", line 457, in <module>
    class XAxis(Axis):
  File "/home/name/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axis3d.py", line 458, in XAxis
    get_view_interval, set_view_interval = maxis._make_getset_interval(
AttributeError: module 'matplotlib.axis' has no attribute '_make_getset_interval'

So for now I would suggest matplotlib>=2.1.2,<=3.1.0
At least based on my experience on ubuntu 18

@WillemWybo
no, oddly if I start python3 in terminal with matplotlib version 3.1.1 installed I don't get any error, but when I run code to reproduce issue 81 I get the error above. 3.1.0 is the highest version for me where nothing breaks

**Comment by pythonjam** [comment]
I just tested the multiple installations theory. I executed

sudo apt remove python3-matplotlib python-matplotlib-data

https://askubuntu.com/questions/173323/how-do-i-detect-and-remove-python-packages-installed-via-pip
"Pip currently ignores uninstall commands that try to uninstall something owned by the OS"

Then I installed matplotlib 3.3.3. That just introduces a new conflict with numpy:

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "/home/name/blah/NEAT/examples/models/channels/TestCaseEvaluation.py", line 7, in <module>
    from examples.models.channels.channels_hay import Na_Ta
  File "/home/name/blah/NEAT/examples/models/channels/channels_hay.py", line 3, in <module>
    from neat import IonChannel
  File "/home/name/blah/NEAT/neat/__init__.py", line 13, in <module>
    from .trees.morphtree import MorphTree
  File "/home/name/blah/NEAT/neat/trees/morphtree.py", line 13, in <module>
    import matplotlib.patheffects as patheffects
  File "/home/name/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 174, in <module>
    _check_versions()
  File "/home/name/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: numpy.core.multiarray failed to import

Which may indicate that I may also need to get rid of OS owned numpy.
This way it could be a pip3 problem because it does not uninstall OS owned python libraries

**Comment by pythonjam** [comment]
Yes, I think it's likely a pip problem
https://github.com/pypa/pip/issues/4222

**Comment by pythonjam** [comment]
On the general matter of version bumping. Github contains something called "dependabot", which is capable of testing and automatically recommending bumps to newer versions (it automatically generates PR's for that). I have never used it via github but it's supposed to be quite useful for keeping everything up to date.
